apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-sa

 ---

apiVersion: v1  
kind: apiVersion: v1
kind: Secret
metadata:
  name: k8s-sa-token
  annotation: 
    kubenetes.io/service-account.name: k8s-sa
type: kubenetes.io/service-account-token    
