apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my_app
  template:
    metadata:
      labels:
       app: my_app
    spec:
      containers:
        - name: ipapp
          image: harshajain/ip-app:1
          ports:
            - containerPort: 80